### ISSUE TITLE
/rss should return application/xml instead of applicaiton/octet-stream

### ISSUE THREAD

**Issue by GuruCharan94** [lethain/staff-eng#3]
- © Will Larson in the footer points to https://staffeng.com/https://lethain.com
- RSS link at the footer points to https://staffeng.com/rss which downloads a file and not render XML which I expected.  Although if I visit https://staffeng.com/rss.xml , I am able to see the XML feed.

**Comment by lethain** [comment]
Lethain.com link is fixed., wr /rss and /rss.xml, the issue is Gatsby mimetype.

`/rss` is

    content-type: application/octet-stream

`/rss.xml` is

    content-type: application/xml

Will have to debug!

**Comment by lethain** [comment]
The rss.xml is a actually a stale file that isn't being generated at all but was created once a while ago. Digging into gatsby a fair amount, it's unclear to me how I change the content type for the generated RSS file without adding the file extension (which would break existing RSS consumers), so I will retitle this ticket to leave the RSS issue open, but anticipate it's unlikely I will fix it.

**Comment by lethain** [comment]
I spent more time reflecting on the underlying issue here, and basically as a static site where I don't control the server, I have no way to supply the content-type of the static file, so I believe this is unfixable except by adding `.xml` extension and breaking all existing RSS feed subscriptions, which I choose not to do, so unfortunately I believe the remainder of this ticket is unfixable. 😞
